name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  echo_tester:
    container_name: echo_tester
    depends_on:
    - server
    entrypoint:
    - /bin/sh
    - ./validar-echo-server.sh
    image: alpine:latest
    networks:
    - testing_net
    volumes:
    - ./validar-echo-server.sh:/validar-echo-server.sh
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
