name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
  echo_tester:
    container_name: echo_tester
    depends_on:
    - server
    entrypoint: ./validar-echo-server.sh server 12345
    image: ubuntu:latest
    networks:
    - testing_net
